#!/usr/bin/env bash

# Update package lists
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Allow 'Nginx HTTP' through the firewall
ufw allow 'Nginx HTTP'

# Replace the content of the default index page
echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# Add a custom HTTP header and a redirect in the Nginx default server block
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
