#!/usr/bin/env bash
# Setup load balncer 

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 418619-web-01 	54.237.5.178:80 check
    server 418619-web-02 	100.25.146.254:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
