#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Edit config file
sudo tee /etc/haproxy/haproxy.cfg <<EOF
frontend web
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    option http-server-close
    server 418619-web-01 54.227.201.4:80 check
    server 418619-web-02 34.207.121.32:80 check
EOF

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
