#!/usr/bin/env bash
# The file /etc/passwd has already been covered in a previous project and 
# you should be familiar with it. Today we will make up a story based on it
# Write a Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS.

list="/etc/passwd"
f1=""
f2=""
f3=""
f4=""
f5=""
f6=""
f7=""
while IFS= read -r  l
do
	f1="$(echo "l" | cut -d":" -f1)"
	f2="$(echo "l" | cut -d":" -f4)"
	f3="$(echo "l" | cut -d":" -f6)"
	f4="$(echo "l" | cut -d":" -f7)"
	f5="$(echo "l" | cut -d":" -f3)"
	f6="$(echo "l" | cut -d":" -f2)"
	f7="$(echo "l" | cut -d":" -f5)"
	echo "The user $(f1) is part of the $(f2) gang, lives in $(f3) and rides $(f4). $(f5) place is protected by the passcode $(f6), more info about the user here: $(f7)"
done < "$list"
