#!/usr/bin/env bash
# write a Bash script that groups visitors by IP
# and HTTP status code, and displays this data

file="apache-access.log"

awk -f' ' '{print $1, $9}' $file | sort | uniq -c | sort -rn
