#!/usr/bin/env bash
# Write a Bash that displays the time for 12 hrs and 59 mins
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "Minute: $minute"
		((minute++))
	done
	((hour++))
done
