#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with
# the below requirements
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/new_hosts.new
echo "localhost		127.0.0.2" > ~/new_hosts.new
echo "facebook.com	8.8.8.8" >> ~/new_hosts.new
cp -f ~/new_hosts.new /etc/hosts
