#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with
# the below requirements
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

icp /etc/hosts ~/new_hosts.new
echo "127.0.0.2		localhost" > ~/new_hosts.new
echo "8.8.8.8		facebook.com" >> ~/new_hosts.new
cp -f ~/new_hosts.new /etc/hosts
